### ISSUE TITLE
improve "A JSONObject text must begin with '{' at character 1 of" error message

### ISSUE THREAD

**Issue by ralfhauser** [jettison-json/jettison#46]
at org.codehaus.jettison.json.JSONTokener.syntaxError(JSONTokener.java:463)
	at org.codehaus.jettison.json.JSONObject.<init>(JSONObject.java:206)
	at org.codehaus.jettison.json.JSONObject.<init>(JSONObject.java:313)

and then it cites the JSON where "{" is in the first position ?!?!

==> it turns out the by moving the json file from Windows to the invisble "\uFEFF" is prefixed (byte order mark (BOM))

==> please visualize that too !

**Comment by coheigea** [comment]
@ralfhauser Can you provide some sample json?

**Comment by NoelZehnder** [comment]
@coheigea You can find the mentiond json and a linux cmd for showing the invisible characters below:
- [20220922_InvalidJson_BOM.txt](https://github.com/jettison-json/jettison/files/9623084/20220922_InvalidJson_BOM.txt)
- cat -vte 20220922_InvalidJson_BOM.txt | less

**Comment by ralfhauser** [comment]
"cat -vte " shows you

![grafik](https://user-images.githubusercontent.com/1681677/191679639-7784bbb3-47d4-4334-b7b6-4612b01fb11f.png)
